<?php
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder {
	public function run() {
		$countries = [

			[ 'Afghanistan', 'AF', 'AFG', '4', 'AFN', 'Afghani', '؋' ],
			[ 'Albania', 'AL', 'ALB', '8', 'ALL', 'Lek', 'Lek' ],
			[ 'Algeria', 'DZ', 'DZA', '12', 'DZD', 'Dinar', null ],
			[ 'American Samoa', 'AS', 'ASM', '16', 'USD', 'Dollar', '$' ],
			[ 'Andorra', 'AD', 'AND', '20', 'EUR', 'Euro', '€' ],
			[ 'Angola', 'AO', 'AGO', '24', 'AOA', 'Kwanza', 'Kz' ],
			[ 'Anguilla', 'AI', 'AIA', '660', 'XCD', 'Dollar', '$' ],
			[ 'Antarctica', 'AQ', 'ATA', '10', '', '', null ],
			[ 'Antigua and Barbuda', 'AG', 'ATG', '28', 'XCD', 'Dollar', '$' ],
			[ 'Argentina', 'AR', 'ARG', '32', 'ARS', 'Peso', '$' ],
			[ 'Armenia', 'AM', 'ARM', '51', 'AMD', 'Dram', null ],
			[ 'Aruba', 'AW', 'ABW', '533', 'AWG', 'Guilder', 'ƒ' ],
			[ 'Australia', 'AU', 'AUS', '36', 'AUD', 'Dollar', '$' ],
			[ 'Austria', 'AT', 'AUT', '40', 'EUR', 'Euro', '€' ],
			[ 'Azerbaijan', 'AZ', 'AZE', '31', 'AZN', 'Manat', 'ман' ],
			[ 'Bahamas', 'BS', 'BHS', '44', 'BSD', 'Dollar', '$' ],
			[ 'Bahrain', 'BH', 'BHR', '48', 'BHD', 'Dinar', null ],
			[ 'Bangladesh', 'BD', 'BGD', '50', 'BDT', 'Taka', null ],
			[ 'Barbados', 'BB', 'BRB', '52', 'BBD', 'Dollar', '$' ],
			[ 'Belarus', 'BY', 'BLR', '112', 'BYR', 'Ruble', 'p.' ],
			[ 'Belgium', 'BE', 'BEL', '56', 'EUR', 'Euro', '€' ],
			[ 'Belize', 'BZ', 'BLZ', '84', 'BZD', 'Dollar', 'BZ$' ],
			[ 'Benin', 'BJ', 'BEN', '204', 'XOF', 'Franc', null ],
			[ 'Bermuda', 'BM', 'BMU', '60', 'BMD', 'Dollar', '$' ],
			[ 'Bhutan', 'BT', 'BTN', '64', 'BTN', 'Ngultrum', null ],
			[ 'Bolivia', 'BO', 'BOL', '68', 'BOB', 'Boliviano', '$b' ],
			[ 'Bosnia and Herzegovina', 'BA', 'BIH', '70', 'BAM', 'Marka', 'KM' ],
			[ 'Botswana', 'BW', 'BWA', '72', 'BWP', 'Pula', 'P' ],
			[ 'Bouvet Island', 'BV', 'BVT', '74', 'NOK', 'Krone', 'kr' ],
			[ 'Brasil', 'BR', 'BRA', '76', 'BRL', 'Real', 'R$' ],
			[ 'British Indian Ocean Territory', 'IO', 'IOT', '86', 'USD', 'Dollar', '$' ],
			[ 'British Virgin Islands', 'VG', 'VGB', '92', 'USD', 'Dollar', '$' ],
			[ 'Brunei', 'BN', 'BRN', '96', 'BND', 'Dollar', '$' ],
			[ 'Bulgaria', 'BG', 'BGR', '100', 'BGN', 'Lev', 'лв' ],
			[ 'Burkina Faso', 'BF', 'BFA', '854', 'XOF', 'Franc', null ],
			[ 'Burundi', 'BI', 'BDI', '108', 'BIF', 'Franc', null ],
			[ 'Cambodia', 'KH', 'KHM', '116', 'KHR', 'Riels', '៛' ],
			[ 'Cameroon', 'CM', 'CMR', '120', 'XAF', 'Franc', 'FCF' ],
			[ 'Canada', 'CA', 'CAN', '124', 'CAD', 'Dollar', '$' ],
			[ 'Cape Verde', 'CV', 'CPV', '132', 'CVE', 'Escudo', null ],
			[ 'Cayman Islands', 'KY', 'CYM', '136', 'KYD', 'Dollar', '$' ],
			[ 'Central African Republic', 'CF', 'CAF', '140', 'XAF', 'Franc', 'FCF' ],
			[ 'Chad', 'TD', 'TCD', '148', 'XAF', 'Franc', null ],
			[ 'Chile', 'CL', 'CHL', '152', 'CLP', 'Peso', null ],
			[ 'China', 'CN', 'CHN', '156', 'CNY', 'Yuan Renminbi', '¥' ],
			[ 'Christmas Island', 'CX', 'CXR', '162', 'AUD', 'Dollar', '$' ],
			[ 'Cocos Islands', 'CC', 'CCK', '166', 'AUD', 'Dollar', '$' ],
			[ 'Colombia', 'CO', 'COL', '170', 'COP', 'Peso', '$' ],
			[ 'Comoros', 'KM', 'COM', '174', 'KMF', 'Franc', null ],
			[ 'Cook Islands', 'CK', 'COK', '184', 'NZD', 'Dollar', '$' ],
			[ 'Costa Rica', 'CR', 'CRI', '188', 'CRC', 'Colon', '₡' ],
			[ 'Croatia', 'HR', 'HRV', '191', 'HRK', 'Kuna', 'kn' ],
			[ 'Cuba', 'CU', 'CUB', '192', 'CUP', 'Peso', '₱' ],
			[ 'Cyprus', 'CY', 'CYP', '196', 'CYP', 'Pound', null ],
			[ 'Czech Republic', 'CZ', 'CZE', '203', 'CZK', 'Koruna', 'Kč' ],
			[ 'Democratic Republic of the Congo', 'CD', 'COD', '180', 'CDF', 'Franc', null ],
			[ 'Denmark', 'DK', 'DNK', '208', 'DKK', 'Krone', 'kr' ],
			[ 'Djibouti', 'DJ', 'DJI', '262', 'DJF', 'Franc', null ],
			[ 'Dominica', 'DM', 'DMA', '212', 'XCD', 'Dollar', '$' ],
			[ 'Dominican Republic', 'DO', 'DOM', '214', 'DOP', 'Peso', 'RD$' ],
			[ 'East Timor', 'TL', 'TLS', '626', 'USD', 'Dollar', '$' ],
			[ 'Ecuador', 'EC', 'ECU', '218', 'USD', 'Dollar', '$' ],
			[ 'Egypt', 'EG', 'EGY', '818', 'EGP', 'Pound', '£' ],
			[ 'El Salvador', 'SV', 'SLV', '222', 'SVC', 'Colone', '$' ],
			[ 'Equatorial Guinea', 'GQ', 'GNQ', '226', 'XAF', 'Franc', 'FCF' ],
			[ 'Eritrea', 'ER', 'ERI', '232', 'ERN', 'Nakfa', 'Nfk' ],
			[ 'Estonia', 'EE', 'EST', '233', 'EEK', 'Kroon', 'kr' ],
			[ 'Ethiopia', 'ET', 'ETH', '231', 'ETB', 'Birr', null ],
			[ 'Falkland Islands', 'FK', 'FLK', '238', 'FKP', 'Pound', '£' ],
			[ 'Faroe Islands', 'FO', 'FRO', '234', 'DKK', 'Krone', 'kr' ],
			[ 'Fiji', 'FJ', 'FJI', '242', 'FJD', 'Dollar', '$' ],
			[ 'Finland', 'FI', 'FIN', '246', 'EUR', 'Euro', '€' ],
			[ 'France', 'FR', 'FRA', '250', 'EUR', 'Euro', '€' ],
			[ 'French Guiana', 'GF', 'GUF', '254', 'EUR', 'Euro', '€' ],
			[ 'French Polynesia', 'PF', 'PYF', '258', 'XPF', 'Franc', null ],
			[ 'French Southern Territories', 'TF', 'ATF', '260', 'EUR', 'Euro', 'currency_symbol' => '€' ],
			[ 'Gabon', 'GA', 'GAB', '266', 'XAF', 'Franc', 'FCF' ],
			[ 'Gambia', 'GM', 'GMB', '270', 'GMD', 'Dalasi', 'D' ],
			[ 'Georgia', 'GE', 'GEO', '268', 'GEL', 'Lari', null ],
			[ 'Germany', 'DE', 'DEU', '276', 'EUR', 'Euro', '€' ],
			[ 'Ghana', 'GH', 'GHA', '288', 'GHC', 'Cedi', '¢' ],
			[ 'Gibraltar', 'GI', 'GIB', '292', 'GIP', 'Pound', '£' ],
			[ 'Greece', 'GR', 'GRC', '300', 'EUR', 'Euro', '€' ],
			[ 'Greenland', 'GL', 'GRL', '304', 'DKK', 'Krone', 'kr' ],
			[ 'Grenada', 'GD', 'GRD', '308', 'XCD', 'Dollar', '$' ],
			[ 'Guadeloupe', 'GP', 'GLP', '312', 'EUR', 'Euro', '€' ],
			[ 'Guam', 'GU', 'GUM', '316', 'USD', 'Dollar', '$' ],
			[ 'Guatemala', 'GT', 'GTM', '320', 'GTQ', 'Quetzal', 'Q' ],
			[ 'Guinea', 'GN', 'GIN', '324', 'GNF', 'Franc', null ],
			[ 'Guinea-Bissau', 'GW', 'GNB', '624', 'XOF', 'Franc', null ],
			[ 'Guyana', 'GY', 'GUY', '328', 'GYD', 'Dollar', '$' ],
			[ 'Haiti', 'HT', 'HTI', '332', 'HTG', 'Gourde', 'G' ],
			[ 'Heard Island and McDonald Islands', 'HM', 'HMD', '334', 'AUD', 'Dollar', '$' ],
			[ 'Honduras', 'HN', 'HND', '340', 'HNL', 'Lempira', 'L' ],
			[ 'Hong Kong', 'HK', 'HKG', '344', 'HKD', 'Dollar', '$' ],
			[ 'Hungary', 'HU', 'HUN', '348', 'HUF', 'Forint', 'Ft' ],
			[ 'Iceland', 'IS', 'ISL', '352', 'ISK', 'Krona', 'kr' ],
			[ 'India', 'IN', 'IND', '356', 'INR', 'Rupee', '₹' ],
			[ 'Indonesia', 'ID', 'IDN', '360', 'IDR', 'Rupiah', 'Rp' ],
			[ 'Iran', 'IR', 'IRN', '364', 'IRR', 'Rial', '﷼' ],
			[ 'Iraq', 'IQ', 'IRQ', '368', 'IQD', 'Dinar', null ],
			[ 'Ireland', 'IE', 'IRL', '372', 'EUR', 'Euro', '€' ],
			[ 'Israel', 'IL', 'ISR', '376', 'ILS', 'Shekel', '₪' ],
			[ 'Italy', 'IT', 'ITA', '380', 'EUR', 'Euro', '€' ],
			[ 'Ivory Coast', 'CI', 'CIV', '384', 'XOF', 'Franc', null ],
			[ 'Jamaica', 'JM', 'JAM', '388', 'JMD', 'Dollar', '$' ],
			[ 'Japan', 'JP', 'JPN', '392', 'JPY', 'Yen', '¥' ],
			[ 'Jordan', 'JO', 'JOR', '400', 'JOD', 'Dinar', null ],
			[ 'Kazakhstan', 'KZ', 'KAZ', '398', 'KZT', 'Tenge', 'лв' ],
			[ 'Kenya', 'KE', 'KEN', '404', 'KES', 'Shilling', null ],
			[ 'Kiribati', 'KI', 'KIR', '296', 'AUD', 'Dollar', '$' ],
			[ 'Kuwait', 'KW', 'KWT', '414', 'KWD', 'Dinar', null ],
			[ 'Kyrgyzstan', 'KG', 'KGZ', '417', 'KGS', 'Som', 'лв' ],
			[ 'Laos', 'LA', 'LAO', '418', 'LAK', 'Kip', '₭' ],
			[ 'Latvia', 'LV', 'LVA', '428', 'LVL', 'Lat', 'Ls' ],
			[ 'Lebanon', 'LB', 'LBN', '422', 'LBP', 'Pound', '£' ],
			[ 'Lesotho', 'LS', 'LSO', '426', 'LSL', 'Loti', 'L' ],
			[ 'Liberia', 'LR', 'LBR', '430', 'LRD', 'Dollar', '$' ],
			[ 'Libya', 'LY', 'LBY', '434', 'LYD', 'Dinar', null ],
			[ 'Liechtenstein', 'LI', 'LIE', '438', 'CHF', 'Franc', 'CHF' ],
			[ 'Lithuania', 'LT', 'LTU', '440', 'LTL', 'Litas', 'Lt' ],
			[ 'Luxembourg', 'LU', 'LUX', '442', 'EUR', 'Euro', '€' ],
			[ 'Macao', 'MO', 'MAC', '446', 'MOP', 'Pataca', 'MOP' ],
			[ 'Macedonia', 'MK', 'MKD', '807', 'MKD', 'Denar', 'ден' ],
			[ 'Madagascar', 'MG', 'MDG', '450', 'MGA', 'Ariary', null ],
			[ 'Malawi', 'MW', 'MWI', '454', 'MWK', 'Kwacha', 'MK' ],
			[ 'Malaysia', 'MY', 'MYS', '458', 'MYR', 'Ringgit', 'RM' ],
			[ 'Maldives', 'MV', 'MDV', '462', 'MVR', 'Rufiyaa', 'Rf' ],
			[ 'Mali', 'ML', 'MLI', '466', 'XOF', 'Franc', null ],
			[ 'Malta', 'MT', 'MLT', '470', 'MTL', 'Lira', null ],
			[ 'Marshall Islands', 'MH', 'MHL', '584', 'USD', 'Dollar', '$' ],
			[ 'Martinique', 'MQ', 'MTQ', '474', 'EUR', 'Euro', '€' ],
			[ 'Mauritania', 'MR', 'MRT', '478', 'MRO', 'Ouguiya', 'UM' ],
			[ 'Mauritius', 'MU', 'MUS', '480', 'MUR', 'Rupee', '₨' ],
			[ 'Mayotte', 'YT', 'MYT', '175', 'EUR', 'Euro', '€' ],
			[ 'Mexico', 'MX', 'MEX', '484', 'MXN', 'Peso', '$' ],
			[ 'Micronesia', 'FM', 'FSM', '583', 'USD', 'Dollar', '$' ],
			[ 'Moldova', 'MD', 'MDA', '498', 'MDL', 'Leu', null ],
			[ 'Monaco', 'MC', 'MCO', '492', 'EUR', 'Euro', '€' ],
			[ 'Mongolia', 'MN', 'MNG', '496', 'MNT', 'Tugrik', '₮' ],
			[ 'Montserrat', 'MS', 'MSR', '500', 'XCD', 'Dollar', '$' ],
			[ 'Morocco', 'MA', 'MAR', '504', 'MAD', 'Dirham', null ],
			[ 'Mozambique', 'MZ', 'MOZ', '508', 'MZN', 'Meticail', 'MT' ],
			[ 'Myanmar', 'MM', 'MMR', '104', 'MMK', 'Kyat', 'K' ],
			[ 'Namibia', 'NA', 'NAM', '516', 'NAD', 'Dollar', '$' ],
			[ 'Nauru', 'NR', 'NRU', '520', 'AUD', 'Dollar', '$' ],
			[ 'Nepal', 'NP', 'NPL', '524', 'NPR', 'Rupee', '₨' ],
			[ 'Netherlands', 'NL', 'NLD', '528', 'EUR', 'Euro', '€' ],
			[ 'Netherlands Antilles', 'AN', 'ANT', '530', 'ANG', 'Guilder', 'ƒ' ],
			[ 'New Caledonia', 'NC', 'NCL', '540', 'XPF', 'Franc', null ],
			[ 'New Zealand', 'NZ', 'NZL', '554', 'NZD', 'Dollar', '$' ],
			[ 'Nicaragua', 'NI', 'NIC', '558', 'NIO', 'Cordoba', 'C$' ],
			[ 'Niger', 'NE', 'NER', '562', 'XOF', 'Franc', null ],
			[ 'Nigeria', 'NG', 'NGA', '566', 'NGN', 'Naira', '₦' ],
			[ 'Niue', 'NU', 'NIU', '570', 'NZD', 'Dollar', '$' ],
			[ 'Norfolk Island', 'NF', 'NFK', '574', 'AUD', 'Dollar', '$' ],
			[ 'North Korea', 'KP', 'PRK', '408', 'KPW', 'Won', '₩' ],
			[ 'Northern Mariana Islands', 'MP', 'MNP', '580', 'USD', 'Dollar', '$' ],
			[ 'Norway', 'NO', 'NOR', '578', 'NOK', 'Krone', 'kr' ],
			[ 'Oman', 'OM', 'OMN', '512', 'OMR', 'Rial', '﷼' ],
			[ 'Pakistan', 'PK', 'PAK', '586', 'PKR', 'Rupee', '₨' ],
			[ 'Palau', 'PW', 'PLW', '585', 'USD', 'Dollar', '$' ],
			[ 'Palestinian Territory', 'PS', 'PSE', '275', 'ILS', 'Shekel', '₪' ],
			[ 'Panama', 'PA', 'PAN', '591', 'PAB', 'Balboa', 'B/.' ],
			[ 'Papua New Guinea', 'PG', 'PNG', '598', 'PGK', 'Kina', null, ],
			[ 'Paraguay', 'PY', 'PRY', '600', 'PYG', 'Guarani', 'Gs', ],
			[ 'Peru', 'PE', 'PER', '604', 'PEN', 'Sol', 'S/.' ],
			[ 'Philippines', 'PH', 'PHL', '608', 'PHP', 'Peso', 'Php' ],
			[ 'Pitcairn', 'PN', 'PCN', '612', 'NZD', 'Dollar', '$' ],
			[ 'Poland', 'PL', 'POL', '616', 'PLN', 'Zloty', 'zł' ],
			[ 'Portugal', 'PT', 'PRT', '620', 'EUR', 'Euro', '€' ],
			[ 'Puerto Rico', 'PR', 'PRI', '630', 'USD', 'Dollar', '$' ],
			[ 'Qatar', 'QA', 'QAT', '634', 'QAR', 'Rial', '﷼' ],
			[ 'Republic of the Congo', 'CG', 'COG', '178', 'XAF', 'Franc', 'FCF' ],
			[ 'Reunion', 'RE', 'REU', '638', 'EUR', 'Euro', '€' ],
			[ 'Romania', 'RO', 'ROU', '642', 'RON', 'Leu', 'lei' ],
			[ 'Russia', 'RU', 'RUS', '643', 'RUB', 'Ruble', 'руб' ],
			[ 'Rwanda', 'RW', 'RWA', '646', 'RWF', 'Franc', null ],
			[ 'Saint Helena', 'SH', 'SHN', '654', 'SHP', 'Pound', '£' ],
			[ 'Saint Kitts and Nevis', 'KN', 'KNA', '659', 'XCD', 'Dollar', '$' ],
			[ 'Saint Lucia', 'LC', 'LCA', '662', 'XCD', 'Dollar', '$' ],
			[ 'Saint Pierre and Miquelon', 'PM', 'SPM', '666', 'EUR', 'Euro', '€' ],
			[ 'Saint Vincent and the Grenadines', 'VC', 'VCT', '670', 'XCD', 'Dollar', '$' ],
			[ 'Samoa', 'WS', 'WSM', '882', 'WST', 'Tala', 'WS$' ],
			[ 'San Marino', 'SM', 'SMR', '674', 'EUR', 'Euro', '€' ],
			[ 'Sao Tome and Principe', 'ST', 'STP', '678', 'STD', 'Dobra', 'Db' ],
			[ 'Saudi Arabia', 'SA', 'SAU', '682', 'SAR', 'Rial', '﷼' ],
			[ 'Senegal', 'SN', 'SEN', '686', 'XOF', 'Franc', null ],
			[ 'Serbia and Montenegro', 'CS', 'SCG', '891', 'RSD', 'Dinar', 'Дин' ],
			[ 'Seychelles', 'SC', 'SYC', '690', 'SCR', 'Rupee', '₨' ],
			[ 'Sierra Leone', 'SL', 'SLE', '694', 'SLL', 'Leone', 'Le' ],
			[ 'Singapore', 'SG', 'SGP', '702', 'SGD', 'Dollar', '$' ],
			[ 'Slovakia', 'SK', 'SVK', '703', 'SKK', 'Koruna', 'Sk' ],
			[ 'Slovenia', 'SI', 'SVN', '705', 'EUR', 'Euro', '€' ],
			[ 'Solomon Islands', 'SB', 'SLB', '90', 'SBD', 'Dollar', '$' ],
			[ 'Somalia', 'SO', 'SOM', '706', 'SOS', 'Shilling', 'S' ],
			[ 'South Africa', 'ZA', 'ZAF', '710', 'ZAR', 'Rand', 'R' ],
			[ 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239', 'GBP', 'Pound', '£' ],
			[ 'South Korea', 'KR', 'KOR', '410', 'KRW', 'Won', '₩' ],
			[ 'Spain', 'ES', 'ESP', '724', 'EUR', 'Euro', '€' ],
			[ 'Sri Lanka', 'LK', 'LKA', '144', 'LKR', 'Rupee', '₨' ],
			[ 'Sudan', 'SD', 'SDN', '736', 'SDD', 'Dinar', null ],
			[ 'Suriname', 'SR', 'SUR', '740', 'SRD', 'Dollar', '$' ],
			[ 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744', 'NOK', 'Krone', 'kr' ],
			[ 'Swaziland', 'SZ', 'SWZ', '748', 'SZL', 'Lilangeni', null ],
			[ 'Sweden', 'SE', 'SWE', '752', 'SEK', 'Krona', 'kr' ],
			[ 'Switzerland', 'CH', 'CHE', '756', 'CHF', 'Franc', 'CHF' ],
			[ 'Syria', 'SY', 'SYR', '760', 'SYP', 'Pound', '£' ],
			[ 'Taiwan', 'TW', 'TWN', '158', 'TWD', 'Dollar', 'NT$' ],
			[ 'Tajikistan', 'TJ', 'TJK', '762', 'TJS', 'Somoni', null ],
			[ 'Tanzania', 'TZ', 'TZA', '834', 'TZS', 'Shilling', null ],
			[ 'Thailand', 'TH', 'THA', '764', 'THB', 'Baht', '฿' ],
			[ 'Togo', 'TG', 'TGO', '768', 'XOF', 'Franc', null ],
			[ 'Tokelau', 'TK', 'TKL', '772', 'NZD', 'Dollar', '$' ],
			[ 'Tonga', 'TO', 'TON', '776', 'TOP', 'Pa\'anga', 'T$' ],
			[ 'Trinidad and Tobago', 'TT', 'TTO', '780', 'TTD', 'Dollar', 'TT$' ],
			[ 'Tunisia', 'TN', 'TUN', '788', 'TND', 'Dinar', null ],
			[ 'Turkey', 'TR', 'TUR', '792', 'TRY', 'Lira', 'YTL' ],
			[ 'Turkmenistan', 'TM', 'TKM', '795', 'TMM', 'Manat', 'm' ],
			[ 'Turks and Caicos Islands', 'TC', 'TCA', '796', 'USD', 'Dollar', '$' ],
			[ 'Tuvalu', 'TV', 'TUV', '798', 'AUD', 'Dollar', '$' ],
			[ 'U. S. Virgin Islands', 'VI', 'VIR', '850', 'USD', 'Dollar', '$' ],
			[ 'Uganda', 'UG', 'UGA', '800', 'UGX', 'Shilling', null ],
			[ 'Ukraine', 'UA', 'UKR', '804', 'UAH', 'Hryvnia', '₴' ],
			[ 'United Arab Emirates', 'AE', 'ARE', '784', 'AED', 'Dirham', null ],
			[ 'United Kingdom', 'GB', 'GBR', '826', 'GBP', 'Pound', '£' ],
			[ 'United States', 'US', 'USA', '840', 'USD', 'Dollar', '$' ],
			[ 'United States Minor Outlying Islands', 'UM', 'UMI', '581', 'USD', 'Dollar ', '$' ],
			[ 'Uruguay', 'UY', 'URY', '858', 'UYU', 'Peso', '$U' ],
			[ 'Uzbekistan', 'UZ', 'UZB', '860', 'UZS', 'Som', 'лв' ],
			[ 'Vanuatu', 'VU', 'VUT', '548', 'VUV', 'Vatu', 'Vt' ],
			[ 'Vatican', 'VA', 'VAT', '336', 'EUR', 'Euro', '€' ],
			[ 'Venezuela', 'VE', 'VEN', '862', 'VEF', 'Bolivar', 'Bs' ],
			[ 'Vietnam', 'VN', 'VNM', '704', 'VND', 'Dong', '₫' ],
			[ 'Wallis and Futuna', 'WF', 'WLF', '876', 'XPF', 'Franc', null ],
			[ 'Western Sahara', 'EH', 'ESH', '732', 'MAD', 'Dirham', null ],
			[ 'Yemen', 'YE', 'YEM', '887', 'YER', 'Rial', '﷼' ],
			[ 'Zambia', 'ZM', 'ZMB', '894', 'ZMK', 'Kwacha', 'ZK' ],
			[ 'Zimbabwe', 'ZW', 'ZWE', '716', 'ZWD', 'Dollar', 'Z$' ]
		];

		$data_arr = [];

		foreach( $countries as $i => $country )
		{
			$data_arr[] = [

				'id'               => $i +1,
				'name'             => $country[0],
				'iso_alpha2'       => $country[1],
				'iso_alpha3'       => $country[2],
				'iso_numeric'      => $country[3],
				'currency_code'    => $country[4],
				'currency_name'    => $country[5],
				'currrency_symbol' => isset($country[6])?$country[6]:null
			];
		}

		DB::statement('SET foreign_key_checks = 0');
		DB::table('country')->truncate();
		DB::table('country')->insert( $data_arr );
		DB::statement('SET foreign_key_checks = 1');
	}
}
